/**
 * Pages Controller
 *
 * Handles static and informational pages (about, FAQ, licenses, changelog, contact)
 */

import type { Request, Response } from 'express';
import { ChangelogService } from '../../application/services/ChangelogService.js';

export class PagesController {
  private readonly changelogService: ChangelogService;

  constructor() {
    this.changelogService = new ChangelogService();
  }

  /**
   * Show About page
   */
  getAbout(req: Request, res: Response): void {
    res.render('pages/about', {
      title: 'About - TaskFlow',
      user: (req as { user?: unknown }).user,
      locale: req.session.locale ?? 'fr',
    });
  }

  /**
   * Show FAQ page
   */
  getFaq(req: Request, res: Response): void {
    res.render('pages/faq', {
      title: 'FAQ - TaskFlow',
      user: (req as { user?: unknown }).user,
      locale: req.session.locale ?? 'fr',
    });
  }

  /**
   * Show Licenses page
   */
  getLicenses(req: Request, res: Response): void {
    res.render('pages/licenses', {
      title: 'Licenses - TaskFlow',
      user: (req as { user?: unknown }).user,
      locale: req.session.locale ?? 'fr',
    });
  }

  /**
   * Show Changelog page
   */
  getChangelog(req: Request, res: Response): void {
    // Parse CHANGELOG.md file generated by conventional-changelog-cli
    const versions = this.changelogService.parseChangelog();

    // Calculate stats
    let totalCommits = 0;
    const commitTypes = new Map<string, number>();

    for (const version of versions) {
      for (const [type, commits] of version.sections) {
        totalCommits += commits.length;
        commitTypes.set(type, (commitTypes.get(type) ?? 0) + commits.length);
      }
    }

    // Get type labels for rendering
    const typeLabels = new Map<string, { label: string; icon: string; color: string }>();
    for (const type of commitTypes.keys()) {
      typeLabels.set(type, this.changelogService.getTypeLabel(type));
    }

    res.render('pages/changelog', {
      title: 'Changelog - TaskFlow',
      user: (req as { user?: unknown }).user,
      locale: req.session.locale ?? 'fr',
      versions: versions.map((v) => ({
        ...v,
        sections: Object.fromEntries(v.sections),
      })),
      totalCommits,
      commitTypes: Object.fromEntries(commitTypes),
      typeLabels: Object.fromEntries(typeLabels),
    });
  }

  /**
   * Show Contact page (placeholder - redirect to FAQ for now)
   */
  getContact(req: Request, res: Response): void {
    res.render('pages/contact', {
      title: 'Contact - TaskFlow',
      user: (req as { user?: unknown }).user,
      locale: req.session.locale ?? 'fr',
    });
  }
}
